name: ambulance
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: null
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  fluttertoast: ^8.2.8
  geocoding: ^3.0.0
  geolocator: null
  get_it: ^8.0.0
  google_maps_flutter: null
  iconsax: ^0.0.8
  intl: ^0.19.0
  loader_overlay: ^4.0.2+1
  location: ^7.0.0
  permission_handler: ^11.3.1
  shared_preferences: null
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/map_style_night.json

  fonts:
    - family: BoutroSasma
      fonts:
        - asset: assets/fonts/boutrosasma.ttf
